version: "3"

services:

  rx_scraper:
      
      working_dir: /app
      container_name: rx_scraper

      restart: always

      build: .

      expose:
        - "8085"

      ports:
        - "8085:8085"

      command: bash -c "npm run build && node dist/index.js"

      depends_on:
        - browserless

  browserless:

    image: browserless/chrome:latest
    restart: always

    ports:
      - "3000:3000"

    expose: 
      - "3000"
