version: "3"

services:

  rx_scraper:
      
      working_dir: /usr/src/app
      container_name: rx_scraper

      restart: always

      build: .

      expose:
      - "8081"

      ports:
        - "8081:8081"

      command: bash -c "npm run build && node dist/index.js"
